version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gamehub-postgres
    restart: unless-stopped
    env_file:
      - ./.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgadmin_data:
